-- MySQL Script generated by MySQL Workbench
-- Tue Feb 16 09:40:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ebberodBank
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ebberodBank` ;

-- -----------------------------------------------------
-- Schema ebberodBank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ebberodBank` DEFAULT CHARACTER SET utf8 ;
USE `ebberodBank` ;

-- CREATE USER 'bank'@'localhost' IDENTIFIED BY 'Bank1234';
-- GRANT ALL PRIVILEGES ON ebberodBank.* TO 'bank'@'localhost';

-- -----------------------------------------------------
-- Table `ebberodBank`.`bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebberodBank`.`bank` ;

CREATE TABLE IF NOT EXISTS `ebberodBank`.`bank` (
  `bank_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`bank_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebberodBank`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebberodBank`.`customer` ;

CREATE TABLE IF NOT EXISTS `ebberodBank`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `bank_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`),
  FOREIGN KEY (bank_id) REFERENCES bank(bank_id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebberodBank`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebberodBank`.`employee` ;

CREATE TABLE IF NOT EXISTS `ebberodBank`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `bank_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  FOREIGN KEY (bank_id) REFERENCES bank(bank_id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebberodBank`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebberodBank`.`accounts` ;

CREATE TABLE IF NOT EXISTS `ebberodBank`.`accounts` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`account_id`),
  FOREIGN KEY (customer_id) REFERENCES customer(customer_id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebberodBank`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebberodBank`.`transactions` ;

CREATE TABLE IF NOT EXISTS `ebberodBank`.`transactions` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  FOREIGN KEY (account_id) REFERENCES accounts(account_id))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
